### ISSUE TITLE
Autodeploy doesn't work with provided `run` script

### ISSUE THREAD

**Issue by besza** [IvoNet/jakartaee8-payara-microprofile-archetype#1]
After successfully generating a project from this archetype, executing the provided `run` script does not deploy the WAR file in the artifact/ folder.

**Environment**:
Maven: 3.6.2
Java: openjdk 11.0.5
Docker: 19.03.4-ce, build 9013bf583a
OS:  Linux 4.19.80-1-MANJARO

**Comment by IvoNet** [comment]
Are you using Java 11+ for your project?
This archetype is to stimulate usage of Java 11 and won't work anymore with lower versions...

**Comment by IvoNet** [comment]
Oh I see.. There is a bug. I fixing it now

**Comment by besza** [comment]
Yes, I'm using OpenJDK 11.

Autodeploy seems to work when I use an absolute path for the docker volume:
`-v "$(pwd)/artifact:/opt/payara/payara5/glassfish/domains/domain1/autodeploy"`.

**Comment by IvoNet** [comment]
that's it... will fix to "/opt/payara/payara5/glassfish/domains/domain1/autodeploy"

**Comment by IvoNet** [comment]
there was a problem in minikube/microk8s when using symlinks in docker images

**Comment by IvoNet** [comment]
should work now ... use version 1.1 in the initializr: http://ivo2u.nl/oq
Thanks for the feedback!
